### PR TITLE
Add the transformedCheck() function

### PR DESCRIPTION
**Pull request by tomphp**
When used with https://github.com/tomphp/php-transform, this replaces:

``` php
$dates = [ /* array of DateTime objects */ ];

$datesFor2015 = array_filter(
    $dates,
    function (DateTime $date) {
        return $date->format('Y') === '2015';
    }
);
```

with: 

``` php
use Pentathal as P;
use TomPHP\Transform as T;

$dates = [ /* array of DateTime objects */ ];

$datesFor2015 = array_filter(
    $dates,
    P\transformedCheck(T\callMethod('format', 'Y'), P\isSame('2015'))
);
```

Question: is there a better name for this function?

### CODE REVIEW

**Comment by gmazzap** [comment]
Love the idea, very thanks @tomphp, not sure about the naming though.

I would go with something like `applyAfter()` I find is more consistent with the rest of the function names.

``` php
array_filter($data, applyAfter($callable, $predicate));
```

looks nice imo.

Moreover, when we are done discussing, can you please send the PR to `dev` branch? I had not the time to write proper `CONTRIBUTING.md`...

**Comment by tomphp** [comment]
@Giuseppe-Mazzapica great, I prefer `applyAfter` also. I'll update the PR and submit to dev shortly.

**Comment by tomphp** [comment]
I've renamed the function but I can't change the target branch of the PR. Shall I leave it for you to merge it into `dev` or do you want me to open a new PR?

**Comment by gmazzap** [comment]
@tomphp I manually merged from your fork into `dev`, so going to close this. Thanks!

**Pull request closed without merging**
